version: '3.8'
services:
  go_service:
    build: ./go_service
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
      - minio

  react_app:
    build: ./asset-uploader
    ports:
      - "3000:3000"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_asset_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./go_service/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001" # Management Console Port
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
